#!/bin/bash


while getopts "u:s:g:" opt; do
    case $opt in
        u)
            name="$OPTARG"
            ;;
        s)
            shell="$OPTARG"
            ;;
        g)
            groups="$OPTARG"
            ;;
        \?)
            echo "Invalid option: -${OPTARG}"
            exit 1
            ;;
        :)
            echo "Option -${OPTARG} requires an argument."
            exit 1
            ;;
    esac
done


if [ -z "$name" ] || [ -z "$shell" ]; then
    echo "Error: Must provide username and shell."
    exit 1
fi


home_dir="/home/$name"


user_uid=$(awk -F: '{ if ($3 >= max_uid) max_uid=$3 } END { print max_uid + 1 }' /etc/passwd)
user_gid=$user_uid  


echo "Creating new user $name..."
echo "$name:x:$user_uid:$user_gid:$name:$home_dir:$shell" >> /etc/passwd


echo "$name:x:$user_gid:" >> /etc/group
echo "Created primary group/"


if [ -n "$groups" ]; then
    IFS=',' read -ra new_group <<< "$groups"
    for grp in "${new_group[@]}"; do
        
        if ! grep -q "^$grp:" /etc/group; then
            user_gid=$((user_gid + 1))
            echo "$grp:x:$user_gid:" >> /etc/group
        fi
        
        sed -i "/^$grp:/ s/$/,$name/" /etc/group
    done
fi


mkdir -p "$home_dir"
cp -r /etc/skel/. "$home_dir"
chown -R "$name:$name" "$home_dir"
echo "Home directory for '$name' created."

echo "Please enter a password for $name: "
passwd "$name"

echo "User '$name' created. Home directory: '$home_dir'; Shell: '$shell'; Groups: '$groups'."

